package com.declarative.music.lexer.token;

public enum TokenType {
    T_IDENTIFIER,
    T_OPERATOR,
    T_NUMBER,
    T_STRING,
    T_COMMENT,
    T_LET, T_WITH, T_IF, T_FOR, T_RETURN, T_L_PARENTHESIS, T_R_PARENTHESIS, T_L_CURL_PARENTHESIS, T_R_CURL_PARENTHESIS, T_L_QAD_PARENTHESIS, T_R_QAD_PARENTHESIS, T_SEMICOLON, T_COMMA, T_EOF,
    T_PITCH,
    T_RHYTHM
}
